### ISSUE TITLE
Interleavesound conditional integration time set breaking compilation

### ISSUE THREAD

**Issue by ksterne** [SuperDARN/control_programs#2]
Sorry for a long title here, but basically I'm not able to compiled the interleavesound control program with the conditional integration time setting found in: (edit darn fast enters translating to comment)

https://github.com/SuperDARN/control_programs/blob/01d688d4d459c6b5892828de4b660b58331ca06e/qnx4/interleavesound.1.00/interleavesound.c#L185-L197

First I get a warning like:
`interleavesound.c(190): Warning! W202: Symbol 'snd_intt_sc' has been defined, but not referenced`
and then an error of:
`interleavesound.c(201): Error! E1011: Symbol 'snd_intt_sc' has not been declared`

I know this is supposed to be representative of the control program, but I'm finding this section isn't working at least at BKS with the QNX4.25 (/ROS1.25)

**Comment by egthomas** [comment]
@ksterne thanks for testing this, and apologies for the compilation errors.  I think I made that same mistake previously when trying to support variable pulse sequences for the Stereo radars.  I've just pushed a change to the QNX4 interleavesound and normalsound code which will hopefully solve that problem: https://github.com/SuperDARN/control_programs/commit/ff6ee357b0c6c5ee0a6baa9b82fb9504b40cf933

**Comment by ksterne** [comment]
Sounds good!  I see the change, though I went back to the non-conditional setting for the code I'm testing.  I'll close this since you've address the issue (you'll also see I found a typo on at least interleavesound code.  Thanks for addressing this quickly.
